"""
SQLAlchemy ORM models.

Two tables:
  - reports      : one record per uploaded file
  - test_results : one record per extracted test value (many per report)

IMPORTANT: No medical-specific columns (no hemoglobin, glucose, etc.).
           All test data is stored generically as (test_name, value, unit, reference_range).
           This lets the system handle any arbitrary medical test without schema changes.
"""

from datetime import datetime, timezone

from sqlalchemy import (
    Column,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
)
from sqlalchemy.orm import relationship

from database import Base


class Report(Base):
    """Represents one uploaded medical report file."""

    __tablename__ = "reports"

    id = Column(Integer, primary_key=True, index=True)

    # Original filename as provided by the user (display only)
    file_name = Column(String(255), nullable=False)

    # Internal storage path (UUID-based, never the original filename)
    file_path = Column(String(512), nullable=False)

    # MIME type: application/pdf, image/jpeg, image/png
    file_type = Column(String(100), nullable=True)

    # Date extracted from the report content (may be null if not found)
    report_date = Column(String(50), nullable=True)

    # Timestamp of upload
    uploaded_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), nullable=False)

    # Processing pipeline state: uploaded | processing | completed | failed
    processing_status = Column(String(20), default="uploaded", nullable=False)

    # Raw text extracted from the document (PDF text or OCR output)
    ocr_text = Column(Text, nullable=True)

    # Error details if processing_status = failed
    error_message = Column(Text, nullable=True)

    # Relationship: one Report → many TestResult
    test_results = relationship(
        "TestResult",
        back_populates="report",
        cascade="all, delete-orphan",
    )


class TestResult(Base):
    """
    Represents a single test extracted from a medical report.

    Generic structure supports any test type without schema changes.
    """

    __tablename__ = "test_results"

    id = Column(Integer, primary_key=True, index=True)

    # Foreign key to parent report
    report_id = Column(Integer, ForeignKey("reports.id"), nullable=False, index=True)

    # ----- Extracted test data (generic — no medical-specific columns) -----
    test_name = Column(String(255), nullable=False)
    value = Column(String(100), nullable=True)   # stored as string to preserve format
    unit = Column(String(100), nullable=True)
    reference_range = Column(String(200), nullable=True)

    # Date of the specific test (may differ from report_date)
    test_date = Column(String(50), nullable=True)

    # Patient-friendly explanation generated by the explanation service
    explanation = Column(Text, nullable=True)

    # Confidence score from extraction pipeline (null if not reliably available)
    extraction_confidence = Column(Float, nullable=True)

    # Relationship back to parent report
    report = relationship("Report", back_populates="test_results")
